server:
  error:
    include-message: always

eppload:
  scenarios:
    location: C:\Projects\EppLoad\scenarios

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus