server:
  port: 8066
  error:
    include-message: always

eppload:
  scenarios:
    location: C:\Projects\DrsLoad\scenarios

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

epp:
  tcp:
    port: 7000

drs:
  rest:
    uri: http://localhost:8080