CREATE OR REPLACE
PROCEDURE create_loadtest_users
AS
 n_counter NUMBER;
BEGIN
	n_counter := 0;
LOOP
	INSERT
	INTO
	DRPSYS.DRP_DEELNEMER (DNR_ID,
	RGY_ID_AANGESLOTEN_BIJ,
	RGY_ID_VERTEGENWOORDIGT,
	NAAM,
	NAAM_DEELNEMERLIJST,
	DEELNEMERCODE,
	DEELNEMERNUMMER,
	VAN_REGISTRY_JN,
	TAL_CODE,
	TFE_CODE,
	FACTUURBIJLAGE_VIA_EMAIL_JN,
	RVM_CODE,
	REGISTRATIENUMMER,
	MAX_AANTAL_WHOIS,
	URL,
	BUITENLANDSE_DEELNEMER_JN,
	CONTRACT_GETEKEND_JN,
	BERICHTEN_VIA_POLL_JN,
	BERICHTEN_VIA_EMAIL_JN,
	TMS_CODE,
	RDS_CODE,
	TELEFOONNUMMER,
	FAXNUMMER,
	NOTIFYEMAILADRES,
	USER_ID,
	CATEGORIE,
	VERWIJDEREN_JN,
	REKENINGNUMMER_INCASSO,
	TICKETNUMMER,
	BEHOUDEN_DNS_KEY_JN,
	PBLCR_ONDERSTEUNING_DNSSEC_JN,
	INSCHRIJFDATUM,
	ACTIVERINGSDATUM,
	DATUM_OPZEGGING,
	INGANGSDATUM_FAILLISSEMENT,
	ONTVANGSTDATUM_BRIEF_CURATOR,
	ONTVANGSTDATUM_VRZK_OPHEFFING,
	IANA_ID,
	WHOIS_URL,
	VERHUIZING_EMAILADRES,
	TOON_RESELLER_IN_DRS_JN,
	LID_VAN_VVR_JN,
	SID,
	ABUSE_TELEFOONNUMMER,
	ABUSE_EMAILADRES)
VALUES (800000 + n_counter,
1,
1,
CONCAT('Registrar', n_counter),
CONCAT('Registrar', n_counter),
n_counter,
800000 + n_counter,
'N',
'dut',
'kwartaal',
'N',
'ANDERS',
'99999999',
5000,
NULL,
'N',
'N',
'N',
'J',
'active',
NULL,
'+31.621718293',
NULL,
'peter.popma@sidn.nl',
'DRS',
'1',
'N',
NULL,
NULL,
'J',
'N',
TIMESTAMP '1997-01-10 14:07:15.000000',
TIMESTAMP '1997-01-10 14:07:15.000000',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
'N',
'J',
NULL,
NULL,
NULL);
	INSERT
	INTO
	DRPSYS.DRP_GEBRUIKER (GBR_ID,
	DNR_ID,
	TGT_CODE,
	NAAM,
	WACHTWOORD,
	ACTIEF_JN,
	ACTIVERINGSREDEN,
	USER_ID,
	VERWIJDEREN_JN,
	TICKETNUMMER,
	VERLOOPDATUM_WACHTWOORD,
	VRIJGEGEVEN_JN,
	MOBIEL_NUMMER,
	INLOGGEN_JN)
VALUES (800000 + n_counter,
800000 + n_counter,
'epp',
800000 + n_counter,
'e1NTSEE1MTJ9eUI4NG5FL2Q2SW9wWEc5NWZZY1p2VENReWE3U3V1Zm9oRGg3c2hDby92RFdDUFJ3U1BMd0V2T3JBaE1EU2M5Y3hyWXRER1VNbVQ3U0twV3lwOHV1UzJJNU56ZGpaREl5',
'J',
NULL,
'peter',
'N',
0,
NULL,
'J',
NULL,
'J');

n_counter := n_counter + 1;
IF
	n_counter = 1000 THEN
      EXIT;
END
IF;
END
LOOP;
END;

DECLARE
BEGIN
  create_loadtest_users();
END;

