DELETE
FROM
	DRPSYS.DRP_CONTACT_ADRES ca
WHERE
	cpn_handle IN (
	SELECT
		cpn_handle
	FROM
		DRPSYS.DRP_CONTACTPERSOON dc
	WHERE
		GBR_ID IN (
		SELECT
			gbr_id
		FROM
			drpsys.drp_gebruiker
		WHERE
			naam LIKE '800%'));

DELETE
FROM
	DRPSYS.DRP_CORRESPONDENTIE_DATA dcd
WHERE
	dcd.cre_id IN (
	SELECT
		cre_id
	FROM
		DRPSYS.DRP_CORRESPONDENTIE dc2
	WHERE
		cpn_handle IN (
		SELECT
			cpn_handle
		FROM
			DRPSYS.DRP_CONTACTPERSOON dc
		WHERE
			GBR_ID IN (
			SELECT
				gbr_id
			FROM
				drpsys.drp_gebruiker
			WHERE
				naam LIKE '800%')));

DELETE
FROM
	DRPSYS.DRP_CORRESPONDENTIE dc2
WHERE
	cpn_handle IN (
	SELECT
		cpn_handle
	FROM
		DRPSYS.DRP_CONTACTPERSOON dc
	WHERE
		GBR_ID IN (
		SELECT
			gbr_id
		FROM
			drpsys.drp_gebruiker
		WHERE
			naam LIKE '800%'));

DELETE
FROM
	DRPSYS.DRP_CORRESPONDENTIE_DATA dcd
WHERE
	dcd.cre_id IN (
	SELECT
		cre_id
	FROM
		DRPSYS.DRP_CORRESPONDENTIE dc2
	WHERE
		dc2.TICKETNUMMER IN (SELECT TICKETNUMMER 
FROM
	DRPSYS.DRP_TRANSACTIE ta
WHERE
	ta.CPN_HANDLE IN (
	SELECT
		cpn_handle
	FROM
		DRPSYS.DRP_CONTACTPERSOON dc
	WHERE
		GBR_ID IN (
		SELECT
			gbr_id
		FROM
			drpsys.drp_gebruiker
		WHERE
			naam LIKE '800%'))));
		

DELETE
	FROM
		DRPSYS.DRP_CORRESPONDENTIE dc2
	WHERE
		dc2.TICKETNUMMER IN (SELECT TICKETNUMMER 
FROM
	DRPSYS.DRP_TRANSACTIE ta
WHERE
	ta.CPN_HANDLE IN (
	SELECT
		cpn_handle
	FROM
		DRPSYS.DRP_CONTACTPERSOON dc
	WHERE
		GBR_ID IN (
		SELECT
			gbr_id
		FROM
			drpsys.drp_gebruiker
		WHERE
			naam LIKE '800%')));		
		
		
DELETE FROM DRPSYS.DRP_TRANSACTIEBERICHT dt2 WHERE TICKETNUMMER IN		
(SELECT TICKETNUMMER 
FROM
	DRPSYS.DRP_TRANSACTIE ta
WHERE
	ta.CPN_HANDLE IN (
	SELECT
		cpn_handle
	FROM
		DRPSYS.DRP_CONTACTPERSOON dc 
	WHERE
		GBR_ID IN (
		SELECT
			gbr_id
		FROM
			drpsys.DRP_GEBRUIKER dg 
		WHERE
			naam LIKE '800%')));
			
DELETE
FROM
	DRPSYS.DRP_TRANSACTIE ta
WHERE
	ta.CPN_HANDLE IN (
	SELECT
		cpn_handle
	FROM
		DRPSYS.DRP_CONTACTPERSOON dc
	WHERE
		GBR_ID IN (
		SELECT
			gbr_id
		FROM
			drpsys.drp_gebruiker
		WHERE
			naam LIKE '800%'));

DELETE
FROM
	DRPSYS.DRP_CONTACTPERSOON dc
WHERE
	GBR_ID IN (
	SELECT
		gbr_id
	FROM
		drpsys.drp_gebruiker
	WHERE
		naam LIKE '800%');

DELETE
FROM
	drpsys.DRP_GEBRUIKER_GEBRUIKERSROL dgg
WHERE
	GBR_ID IN (
	SELECT
		GBR_ID
	FROM
		drpsys.drp_gebruiker
	WHERE
		naam LIKE '800%');

DELETE
FROM
	drpsys.drp_gebruiker
WHERE
	naam LIKE '800%';

DELETE
FROM
	drpsys.DRP_CORRESPONDENTIE_DATA
WHERE
	CRE_ID IN (
	SELECT
		CRE_ID
	FROM
		drpsys.DRP_CORRESPONDENTIE dc
	WHERE
		dc.DNR_ID IN (
		SELECT
			DNR_ID
		FROM
			drpsys.drp_deelnemer
		WHERE
			DEELNEMERNUMMER LIKE '800%'));

DELETE
FROM
	drpsys.DRP_CORRESPONDENTIE dc
WHERE
	dc.DNR_ID IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%');

DELETE FROM drpsys.DRP_CONTACTROL dc WHERE DNM_ID IN	
(SELECT dd.DNM_ID 
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));	
		
DELETE FROM drpsys.DRP_DELEGATION_SIGNER dds WHERE DK_ID IN (SELECT DK_ID FROM drpsys.DRP_DNS_KEY WHERE DNM_ID IN	
(SELECT dd.DNM_ID 
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%')));	
	
DELETE FROM drpsys.DRP_DNS_KEY WHERE DNM_ID IN	
(SELECT dd.DNM_ID 
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));	
		
DELETE FROM drpsys.DRP_AUTHORITATIEF_NAMESERVER dan WHERE DNM_ID IN	
(SELECT dd.DNM_ID 
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));	

DELETE FROM drpsys.DRP_DOMEINNAAM_TRANSACTIE ddt WHERE DNM_ID IN	
(SELECT dd.DNM_ID 
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));	

DELETE FROM drpsys.DRP_INGESCHREVEN_BEPERKING dib WHERE DNM_ID IN	
(SELECT dd.DNM_ID 
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));	
	
DELETE
FROM
	drpsys.DRP_DOMEINNAAM dd 
WHERE
	dd.DNR_ID_BEHEER IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%');

DELETE FROM DRPSYS.DRP_CORRESPONDENTIE_DATA dcd WHERE dcd.CRE_ID IN
(SELECT CRE_ID FROM drpsys.DRP_CORRESPONDENTIE dc WHERE TICKETNUMMER IN
(SELECT TICKETNUMMER 
FROM
	drpsys.DRP_TRANSACTIE dt 
WHERE
	DNR_ID IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%')));
		
DELETE FROM drpsys.DRP_CORRESPONDENTIE dc WHERE TICKETNUMMER IN
(SELECT TICKETNUMMER 
FROM
	drpsys.DRP_TRANSACTIE dt 
WHERE
	DNR_ID IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));

DELETE FROM DRPSYS.DRP_TRANSACTIEBERICHT dt2 WHERE TICKETNUMMER IN
(SELECT TICKETNUMMER 
FROM
	drpsys.DRP_TRANSACTIE dt 
WHERE
	DNR_ID IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%'));
		
DELETE
FROM
	drpsys.DRP_TRANSACTIE dt 
WHERE
	DNR_ID IN (
	SELECT
		DNR_ID
	FROM
		drpsys.drp_deelnemer
	WHERE
		DEELNEMERNUMMER LIKE '800%');
	
DELETE
FROM
	drpsys.drp_deelnemer
WHERE
	DEELNEMERNUMMER LIKE '800%';