package com.peterpopma.drsload.dto.epp;

public enum EppCommand {
    CONTACTCREATE,
    CONTACTUPDATE,
    CONTACTINFO,
    CONTACTDELETE,
    DOMAINCREATE,
    DOMAININFO,
    DOMAINUPDATE,
    DOMAINDELETE,
    DOMAINTRANSFER,
    DOMAINTRANSFERQUERY,
    DOMAINRENEW,
    HOSTCREATE,
    HOSTINFO,
    HOSTUPDATE,
    HOSTDELETE,
    POLL
}
